- name: copy catalogue service to system directories
  ansible.builtin.template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl daemon-reload
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes

- name: start and enable catalogue
  ansible.builtin.service:
    name: catalogue
    state: started
    enabled: yes