- name: nodejs setup
  include_role: 
    name: common
    tasks_from: nodejs

- name: nodejs setup
  include_role:
    name: common
    tasks_from: nodejs

- name: systemd setup
  include_role:
    name: common  
    tasks_from: systemd.yaml